azure/CLI failing due old az cli version (#644)
azure/CLI@v1 is configured to use a very old version of Azure CLI, due to which az functionapp config commands were failing. Remove explicit az cli dependency, letting the action choose az cli version of the agent. 

Error reported due to old az cli version:

ERROR: Please run 'az account set' to select active account.
Error: Error: az cli script failed.
cleaning up container...
MICROSOFT_AZURE_CLI_1665621746187_CONTAINER